### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 1hella**
Update some of the wording and grammar :)

### CODE REVIEW

**Review by siddharthlatest — CHANGES_REQUESTED** [review]
There shouldn't be a hyphen b/w websockets and based or b/w scroll and based. Other changes look good.

**Comment by 1hella** [comment]
@siddharthlatest Ok I changed those back

**Comment by siddharthlatest** [comment]
Awesome, thanks for contributing! 🎉 🎉  

Hope to see you around 👋

**Comment by 1hella** [comment]
@siddharthlatest Thanks :)

**Pull request merged**
